version: '3.4'

services:
  tweaker:
    image: 127.0.0.1:5001/tweaker
    build:
      context: src/
    ports:
      - 2304:2304
    restart: always
    deploy:
#      placement:
#        constraints: [node.role == worker]
      resources:
        limits:
          cpus: "1"
          memory: 8G
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
